languageCode = "en-us"
title = "Bogdan Toader"
author = "Bogdan Toader"
baseURL = "https://bogdantoader.github.io"
#baseURL = "www.mywebsite.com"
canonifyurls = true
theme = "hugo-xmin"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3
[[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    description = "Bogdan Toader's academic website."
    footer = "[Email](mailto:bogdan.toader@yale.edu) | [Scholar](https://scholar.google.co.uk/citations?user=X76IzDMAAAAJ&hl=en) |[LinkedIn](https://www.linkedin.com/in/bogdan-toader/) | [GitHub](https://github.com/bogdantoader)"
