languageCode = "en-us"
title = "Bogdan Toader"
baseURL = "www.mywebsite.com"
theme = "hugo-xmin"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3
[[menu.main]]
    name = "Talks/Travelling"
    url = "/travelling/"
    weight = 4

[params]
    description = "Bogdan Toader's academic website."
    footer = "[Email](mailto:toader@maths.ox.ac.uk) | [LinkedIn](https://www.linkedin.com/in/bogdan-toader/) | [GitHub](https://github.com/bogdantoader)"
