languageCode = "en-us"
title = "Bogdan Toader"
author = "Bogdan Toader"
baseURL = "https://btoader.com"
canonifyurls = true
theme = "hugo-xmin"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    # url = "/#about"
    url = "/"
    weight = 1
# [[menu.main]]
#     name = "Publications"
#     url = "/publications/"
#     weight = 2
[[menu.main]]
    name = "Research"
    url = "/#research"
    weight = 2
# [[menu.main]]
#     name = "Teaching"
#     url = "/teaching/"
#     weight = 3
# [[menu.main]]
#     name = "Talks"
#     url = "/#talks"
#     weight = 4
[[menu.main]]
    name = "Industry"
    url = "/#industry-engagement"
    weight = 5
[[menu.main]]
    name = "CV"
    url = "CV_BogdanToader_2025_06.pdf"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    description = "Bogdan Toader's academic website."
    footer = "© 2018-2025 Bogdan Toader. Powered by Hugo XMin. <button class='theme-button' onclick='switchTheme()'>[Dark/Light/Colours]</button>"
